### ISSUE TITLE
AList v3 Doesn't Seem to Recognize File Type

### ISSUE THREAD

**Issue by DarremMolko** [alist-org/alist#1710] opened 2022-09-18 14:41 UTC
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure it's due to `alist` and not something else(such as `Dependencies` or `Operational`).
- [X] I'm sure I'm using the latest version

### Alist Version / Alist 版本

v3.0.0-rc.1

### Driver used / 使用的存储驱动

Google Drive, OneDrive

### Describe the bug / 问题描述

AList v3 doesn't seem to recognize file type.

### Reproduction / 复现链接

1) Mount AList with DAVx⁵ (https://github.com/bitfireAT/davx5-ose) as Documents Provider
2) Access the mounted AList with the android native Files app
3) Notice that video files are not recognized, instead it shows the type of file as BIN

**Screenshot of AList v2.6.4, working as expected**
![Screenshot_20220918-111820](https://user-images.githubusercontent.com/70179709/190912648-eb6d7e4e-a6da-4313-b73e-bbedac0035fd.jpg)

**Screenshot of AList v3**
![Screenshot_20220918-111801](https://user-images.githubusercontent.com/70179709/190912608-566b0ce2-0fba-4ae8-992b-e99b227c7857.jpg)

### Logs / 日志

```shell
No relevant logs available.
```

**Comment by Xhofe** [comment] 2022-09-19 05:51
unable to reproduce
![image](https://user-images.githubusercontent.com/36558727/190956445-dd904e36-9386-4362-a488-b5d6c12d0375.png)
The `mimetype` of the file returned by alist is correct in my test.

**Comment by DarremMolko** [comment] 2022-09-19 10:13
This happens with Google Drive and OneDrive, not a local video. If I intercept the intent this is what I get:

**USING ALIST VERSION v2.6.4**
```
URI	intent://at.bitfire.davdroid.webdav/document/359#Intent;scheme=content;type=video/mp4;launchFlags=0x3000003;end

VERSION	1
ACTION	android.intent.action.VIEW
DATA	content://at.bitfire.davdroid.webdav/document/359
TYPE	video/mp4
FLAGS	0x3000003

```

**USING ALIST v3.0.0-rc.1**
```
URI	intent://at.bitfire.davdroid.webdav/document/190#Intent;scheme=content;type=application/octet-stream;launchFlags=0x3000003;end

VERSION	1
ACTION	android.intent.action.VIEW
DATA	content://at.bitfire.davdroid.webdav/document/190
TYPE	application/octet-stream
FLAGS	0x3000003

```

**Comment by Xhofe** [comment] 2022-09-19 10:36
The mimetype is identified by file extension, which should be independent of storage provider. 
Onedrive:
![image](https://user-images.githubusercontent.com/36558727/190999679-5cf13b66-86af-45f9-b853-80531a66e691.png)

**Comment by DarremMolko** [comment] 2022-09-19 10:46
Oh, then I'm not really sure what is happening. If I use propget using cadaver (command line WebDAV client) in a video file I still can't get the correct content type:

```
dav:/dav/drive/Movies/> propget Zeros.and.Ones.2021.mkv
Fetching properties for `Zeros.and.Ones.2021.mkv':
DAV: displayname = Zeros.and.Ones.2021.mkv
DAV: getcontenttype = application/octet-stream
DAV: getlastmodified = Mon, 01 Jan 0001 00:00:00 GMT
DAV: getcontentlength = 1764976284
```
This example is using Google Drive.

**Comment by Xhofe** [comment] 2022-09-19 10:54
The only difference between v2 and v3 is:
- v2: the `mimetype` for all files are empty
- v3: try get `mimetype` by file extension and set `application/octet-stream` as default if can't get.

In addition, the result of getting `mimetype` by file extension is usually system related.

I will close this issue after set empty as default instead of `application/octet-stream`, maybe this is the correct behavior.

**Closed** 2022-09-19 10:59 UTC
Labels: bug, question

**Comment by Xhofe** [comment] 2022-09-19 11:06
You can try it now: https://github.com/alist-org/alist/suites/8355931590/artifacts/368195173

**Comment by DarremMolko** [comment] 2022-09-19 11:45
Indeed, that was it, now it's showing the correct content type. Thank you!
