### ISSUE TITLE
Can you change the mounted WEBDAV protocol to the SMB/NFS protocol? Local mount

### ISSUE THREAD

**Issue by v2209** [alist-org/alist#2651] opened 2022-12-08 20:57 UTC
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

Hello:
Can the mounted WEBDAV protocol be changed to the SMB/NFS protocol? Local mount
Similar to RAIDRIVE mount network disk as local SMB share
No need for other three-party additional software to map local or LAN operations
In this way, it is convenient for devices in the LAN that do not support WEBDAV to easily access files in the network disk

that would be a cool feature
This is cool software. Thanks again for your long and selfless dedication!

你好:
能否支持挂载的WEBDAV协议改为SMB/NFS协议?的本地挂载
类似于RAIDRIVE挂载网盘为本地SMB共享
不再需要其他三方额外软件来映射本地或者局域网操作了
这样可方便局域网内不支持WEBDAV的设备轻松访问网盘内文件

那将是个很酷的功能
这是个很酷的软件再次感谢你们长期无私的奉献!

**Comment by BoYanZh** [comment] 2022-12-09 07:04
duplicate of #2106. But sadly, currently there is no ready-to-wear smb server in golang. Maybe NFS is easier as https://github.com/willscott/go-nfs seems useable.

**Closed** 2022-12-24 04:01 UTC
Labels: duplicate, enhancement
